"""Locked remaining content. Development registry only until the complete acceptance gate."""
from sanguosha.model.character import CharacterDefinition
from sanguosha.model.skill import SkillDefinition
from sanguosha.model.enums import Gender, Kingdom, SkillType

REMAINING_DEV_GENERALS = (
    CharacterDefinition('yj2012_xun_you', '荀攸', Kingdom.WEI, 3, Gender.MALE, ('qice', 'zhiyu'), {'pack': 'yj2012', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2012_xun_you', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2012_wang_yi', '王异', Kingdom.WEI, 3, Gender.FEMALE, ('zhenlie', 'miji'), {'pack': 'yj2012', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2012_wang_yi', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2012_cao_zhang', '曹彰', Kingdom.WEI, 4, Gender.MALE, ('jiangchi',), {'pack': 'yj2012', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2012_cao_zhang', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2012_zhong_hui', '钟会', Kingdom.WEI, 4, Gender.MALE, ('quanji', 'zili'), {'pack': 'yj2012', 'implemented': False, 'playable': False, 'development_only': True, 'version': '一将成名2012经典钟会：权计、自立、觉醒获得排异（单觉醒）', 'resource_id': 'general.yj2012_zhong_hui', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2012_liao_hua', '廖化', Kingdom.SHU, 4, Gender.MALE, ('dangxian', 'fuli'), {'pack': 'yj2012', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2012_liao_hua', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2012_guan_xing_zhang_bao', '关兴张苞', Kingdom.SHU, 4, Gender.MALE, ('fuhun',), {'pack': 'yj2012', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2012_guan_xing_zhang_bao', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2012_ma_dai', '马岱', Kingdom.SHU, 4, Gender.MALE, ('mashu', 'qianxi'), {'pack': 'yj2012', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2012_ma_dai', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2012_bu_lianshi', '步练师', Kingdom.WU, 3, Gender.FEMALE, ('anxu', 'zhuiyi'), {'pack': 'yj2012', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2012_bu_lianshi', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2012_cheng_pu', '程普', Kingdom.WU, 4, Gender.MALE, ('lihuo', 'chunlao'), {'pack': 'yj2012', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2012_cheng_pu', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2012_han_dang', '韩当', Kingdom.WU, 4, Gender.MALE, ('gongqi', 'jiefan'), {'pack': 'yj2012', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2012_han_dang', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2012_liu_biao', '刘表', Kingdom.QUN, 4, Gender.MALE, ('zishou', 'zongshi'), {'pack': 'yj2012', 'implemented': False, 'playable': False, 'development_only': True, 'version': '官方修订后的经典刘表：势力数额外摸牌、出牌阶段不能指定其他角色', 'resource_id': 'general.yj2012_liu_biao', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2012_hua_xiong', '华雄', Kingdom.QUN, 6, Gender.MALE, ('shiyong',), {'pack': 'yj2012', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2012_hua_xiong', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2013_cao_chong', '曹冲', Kingdom.WEI, 3, Gender.MALE, ('chengxiang', 'renxin'), {'pack': 'yj2013', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2013_cao_chong', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2013_guo_huai', '郭淮', Kingdom.WEI, 4, Gender.MALE, ('jingce',), {'pack': 'yj2013', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2013_guo_huai', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2013_man_chong', '满宠', Kingdom.WEI, 3, Gender.MALE, ('junxing', 'yuce'), {'pack': 'yj2013', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2013_man_chong', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2013_guan_ping', '关平', Kingdom.SHU, 4, Gender.MALE, ('longyin',), {'pack': 'yj2013', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2013_guan_ping', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2013_jian_yong', '简雍', Kingdom.SHU, 3, Gender.MALE, ('qiaoshui', 'zongshi_jianyong'), {'pack': 'yj2013', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2013_jian_yong', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2013_liu_feng', '刘封', Kingdom.SHU, 4, Gender.MALE, ('xiansi',), {'pack': 'yj2013', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2013_liu_feng', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2013_pan_zhang_ma_zhong', '潘璋马忠', Kingdom.WU, 4, Gender.MALE, ('duodao', 'anjian'), {'pack': 'yj2013', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2013_pan_zhang_ma_zhong', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2013_yu_fan', '虞翻', Kingdom.WU, 3, Gender.MALE, ('zongxuan', 'zhiyan'), {'pack': 'yj2013', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2013_yu_fan', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2013_zhu_ran', '朱然', Kingdom.WU, 4, Gender.MALE, ('danshou',), {'pack': 'yj2013', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2013_zhu_ran', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2013_fu_huanghou', '伏皇后', Kingdom.QUN, 3, Gender.FEMALE, ('zhuikong', 'qiuyuan'), {'pack': 'yj2013', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2013_fu_huanghou', 'portrait_mode': 'static'}),
    CharacterDefinition('yj2013_li_ru', '李儒', Kingdom.QUN, 3, Gender.MALE, ('juece', 'mieji', 'fencheng'), {'pack': 'yj2013', 'implemented': False, 'playable': False, 'development_only': True, 'version': 'QS-v2经典原版修订档案 @ e8768851bd8054db9fd1b63cd6f1feca813590d7', 'resource_id': 'general.yj2013_li_ru', 'portrait_mode': 'static'}),
    CharacterDefinition('shadow_god_liubei', '神刘备', Kingdom.QUN, 6, Gender.MALE, ('longnu', 'jieying_liubei'), {'pack': 'new_gods', 'implemented': False, 'playable': False, 'development_only': True, 'version': '经典6 HP神刘备：龙怒、结营（阴阳转换）', 'resource_id': 'general.shadow_god_liubei', 'portrait_mode': 'dynamic'}),
    CharacterDefinition('shadow_god_luxun', '神陆逊', Kingdom.QUN, 4, Gender.MALE, ('junlve', 'cuike', 'zhanhuo'), {'pack': 'new_gods', 'implemented': False, 'playable': False, 'development_only': True, 'version': '经典神陆逊：军略、摧克、绽火（奇偶军略体系）', 'resource_id': 'general.shadow_god_luxun', 'portrait_mode': 'dynamic'}),
    CharacterDefinition('thunder_god_ganning', '神甘宁', Kingdom.QUN, 6, Gender.MALE, ('poxi', 'jieying_ganning'), {'pack': 'new_gods', 'implemented': False, 'playable': False, 'development_only': True, 'version': '经典神甘宁：魄袭、劫营（初始3/上限6，营标记）', 'resource_id': 'general.thunder_god_ganning', 'portrait_mode': 'dynamic'}),
    CharacterDefinition('thunder_god_zhangliao', '神张辽', Kingdom.QUN, 4, Gender.MALE, ('duorui', 'zhiti'), {'pack': 'new_gods', 'implemented': False, 'playable': False, 'development_only': True, 'version': '经典夺技能神张辽：夺锐、止啼（废栏、临时获得、原主失效）', 'resource_id': 'general.thunder_god_zhangliao', 'portrait_mode': 'dynamic'}),
)

REMAINING_DEV_SKILLS = (
    SkillDefinition('qice', '奇策', '成本为使用提交时全部非空手牌；选非延时锦囊definition及合法目标；整组VirtualCard保留材料列表并按普通牌结算。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('zhiyu', '智愚', '伤后可摸1并公开当前全部手牌；非空且颜色全同令存活来源弃手牌1；公开展示不永久开启观察权。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('zhenlie', '贞烈', '杀/非延时锦囊被指定后可失去1HP；完成濒死后若仍存活则弃来源牌并令该牌对自己无效；Q08裁顺序。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('miji', '秘计', '结束阶段受伤可选n∈[0,已损HP]摸n，随后从当前手牌分配实际获得数量给其他人；每张一次归属。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('jiangchi', '将驰', '摸牌数修改并加turn-scoped限制；多摸禁止use与respond所有杀，少摸+1次数且不限距离；默认不修改。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('quanji', '权计', '受到每1点伤害可摸1并从当前手牌置1权；特殊牌区权可见性需Q07；持权数增加手牌上限。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('zili', '自立', '准备阶段权≥3且未觉醒：减maxHP1，选择摸2/回HP1，然后授予排异来源zili；不得预先拥有排异。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('paiyi', '排异', '仅自立授予后，每出牌阶段1次弃1权，目标摸2后若手牌>自己的手牌，对其伤害1；可选自己。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('dangxian', '当先', '回合开始插入PLAY阶段，独立phase_token，后续正常PLAY使用次数独立；背面跳回合顺序Q08。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('fuli', '伏枥', '限定濒死可回复到min(存活有效势力种数,maxHP)，然后翻面；不是额外回合；失败救起继续濒死。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('fuhun', '父魂', '两手牌普通杀ViewAs；该牌于PLAY造成实际伤害后授予wusheng,paoxiao到回合末，按来源回收。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('qianxi', '潜袭', '准备阶段判定，选有效距离1角色；本回合按判定最终颜色禁止其手牌使用/打出，逐材料按区域检查。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('anxu', '安恤', '一次出牌阶段选两其他人手牌不同，少者选多者背面手牌公开获得，非黑桃步练师摸1。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('zhuiyi', '追忆', '死亡后允许该技能专用最后选择，目标其他存活者排除杀手，摸3再恢复1；无来源死亡不排除。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('lihuo', '疠火', '普通杀可转火；所有火杀可增一个目标；只转换杀造成过伤害则整牌结算结束扣HP1一次。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('chunlao', '醇醪', '结束阶段没有醇时可存至少一杀；濒死时消耗一醇视为濒死者用酒，通过标准酒自救与濒死管线。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('gongqi', '弓骑', '一次出牌阶段弃任意一牌，本回合攻击范围无限，若装备可再弃其他人牌1；不改通用距离。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('jiefan', '解烦', '限定PLAY选角色；按当前席位序依次询问攻击范围含目标者，弃一武器（手或装备）否则目标摸1。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('zishou', '自守', '摸牌阶段可额外摸存活势力数；本回合出牌阶段用牌不能指定其他角色；不跳出牌阶段，回合边界清理限制。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('zongshi', '宗室', '锁定手牌上限+存活有效势力种数，化身势力经SkillRegistry.faction；神当前映射群不自加新势力。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('shiyong', '恃勇', '实际红色杀或带wine标签杀伤后maxHP-1，每次伤害一次；红且酒不重复。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2012'}),
    SkillDefinition('chengxiang', '称象', '伤后公开顶4，选择非空子集且rank总和≤13；选中获得余牌弃置，服务端计算不是仅计数检查。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('renxin', '仁心', '别人HP恰为1伤前可翻面、弃装备牌防整次伤害；费用可来自手或装备，所有移动副作用正常触发。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('jingce', '精策', '每次PLAY结束时统计当前turn_token CardUsedEvent数量≥当前HP则可摸2；response不计，虚拟材料不多计。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('junxing', '峻刑', '一次PLAY至少1手牌弃置，按三大类型集计算补集，对方弃该补集类型手牌1，否则翻面摸成本张数。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('yuce', '御策', '伤后可展示手牌1；有来源才请求来源弃一不同大类型手牌，否则受伤者回复1。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('longyin', '龙吟', 'PLAY合法使用杀时可付一牌，撤销本杀quota计入一次，红色则摸1；多角色发动不重复扣quota。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('qiaoshui', '巧说', 'PLAY开始拼点；胜利下一张基本/非延时锦囊可加一目标（忽略距离）/原有≥2减一；失败禁锦囊到回合末。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('zongshi_jianyong', '纵适', '纵适，拼点胜取对方牌，未胜取自己牌；需拼点揭示结果/弃置前取得窗口，不能等牌被他人获得再取。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('xiansi', '陷嗣', '准备阶段从1-2角色各取1手/装备牌置公开逆；其他人合法用杀窗口可消耗两逆视为对拥有者用普通杀且计次数。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('duodao', '夺刀', '杀伤后付一牌获得来源装备区武器（仍在该位置）；无来源/武器先不提供无意义发动。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('anjian', '暗箭', '杀对目标伤害计算时source不在target攻击范围内则+1；继发铁索伤害不重新触发目标规则。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('zongxuan', '纵玄', '自己的弃置批次中仍在弃牌堆的牌可非空排序置顶，服务端保存ordered_card_ids与批次锁。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('zhiyan', '直言', '结束阶段选角色摸1并公开该牌；若装备先恢复1再由该角色回合外使用该实体装备，合法槽规则照常。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('danshou', '胆守', 'PLAY第k次发动付k牌并选范围内目标；k=1弃其1，2交给你1，3伤1，≥4双方摸2；成功付费再递增。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('zhuikong', '惴恐', '其他人回合开始自己受伤可拼点；赢绑定target本回合只能以自己为角色目标；没赢target至自己的距离忽略。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('qiuyuan', '求援', '被杀指定后选除杀使用者与自己外的其他人，其给闪则只转移实体牌，否则也加为杀目标；去重循环保护。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('juece', '绝策', 'FINISH开始选无手牌角色伤1；不是失去最后手牌即时触发候选。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('mieji', '灭计', '一次PLAY将黑色锦囊手牌置顶，选有手牌他人；其弃1锦囊或2非锦囊，用约束choice不能混搭。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('fencheng', '焚城', '限定PLAY，其他存活人席位序；首人X=1，每人弃≥X或2火伤；下一阈值为上人实际弃数+1，伤害分支令下人X=1。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'yj2013'}),
    SkillDefinition('longnu', '龙怒', 'PLAY开始强制当前转换状态费用与摸1；阴红色手牌视火杀不限距离，阳锦囊视雷杀不限次数，phase末撤销，状态持久交替。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'new_gods'}),
    SkillDefinition('jieying_liubei', '结营', '神刘备结营，自己被重置即重新横置；所有横置角色上限+2为来源绑定光环；FINISH强制横置另一角色。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'new_gods'}),
    SkillDefinition('junlve', '军略', '受到或造成实际伤害获得等量标记；若同时两身份均满足分别计入需Q08核对；HP流失不计。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'new_gods'}),
    SkillDefinition('cuike', '摧克', 'PLAY开始军略奇数可伤1/偶数可横置角色并弃其区域1；后续军略>7可全移并对其他人伤1，逐个处理新增标记。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'new_gods'}),
    SkillDefinition('zhanhuo', '绽火', '限定PLAY消费全部军略，选至多等量横置角色全弃装备，再选其中一个火伤1；无标记不能形成非空目标。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'new_gods'}),
    SkillDefinition('poxi', '魄袭', '一次PLAY先建立仅发动者可看目标手牌grant，可取消；选择双方手牌四种不同花色各1一起弃，根据自弃0/1/2/3/4分支。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'new_gods'}),
    SkillDefinition('jieying_ganning', '劫营', '神甘宁劫营，营为独立来源persistent effect；没人有营才回合开始自得，FINISH可给其他角色，持者回合末移营后夺其所有手牌。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'new_gods'}),
    SkillDefinition('duorui', '夺锐', 'PLAY实际对其他人伤后可废一装备栏并租借其一个合格武将技能，失效作用于指定ownership；目标下回合末/死亡回收；细则Q06。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'new_gods'}),
    SkillDefinition('zhiti', '止啼', '范围内已伤他人上限-1；与范围内已伤者拼点/决斗胜或被其伤害后恢复一废栏；决斗胜不能只依据造成任意伤害。', SkillType.TRIGGERED, {'development_only': True, 'pack': 'new_gods'}),
)
