import { expect, test } from '@playwright/test'

test('two browsers create, join, ready and enter the general draft', async ({ browser }) => {
  const hostContext = await browser.newContext()
  const guestContext = await browser.newContext()
  const host = await hostContext.newPage()
  const guest = await guestContext.newPage()
  await host.goto('/')
  await host.getByLabel('玩家昵称').fill('房主')
  await host.getByRole('button', { name: '创建多人房间' }).click()
  const roomCode = (await host.locator('.room-code-box strong').textContent())?.trim()
  expect(roomCode).toMatch(/^[A-Z0-9]{6}$/)

  await guest.goto('/room/' + roomCode)
  await guest.getByLabel('玩家昵称').fill('来宾')
  await guest.getByRole('button', { name: '加入房间' }).click()
  await expect(guest.getByText(roomCode!)).toBeVisible()
  await guest.getByRole('button', { name: '准备' }).click()
  await host.getByRole('button', { name: '开始游戏' }).click()
  await expect(host.getByRole('heading', { name: '择将入局' })).toBeVisible()
  await expect(guest.getByRole('heading', { name: '择将入局' })).toBeVisible()
  await hostContext.close()
  await guestContext.close()
})

test('five browser contexts can occupy one room before draft', async ({ browser }) => {
  const contexts = await Promise.all(Array.from({ length: 5 }, () => browser.newContext()))
  const pages = await Promise.all(contexts.map((context) => context.newPage()))
  await pages[0].goto('/')
  await pages[0].getByLabel('玩家昵称').fill('玩家1')
  await pages[0].getByRole('button', { name: '创建多人房间' }).click()
  const roomCode = (await pages[0].locator('.room-code-box strong').textContent())?.trim()
  expect(roomCode).toMatch(/^[A-Z0-9]{6}$/)
  for (let index = 1; index < pages.length; index += 1) {
    await pages[index].goto('/room/' + roomCode)
    await pages[index].getByLabel('玩家昵称').fill('玩家' + (index + 1))
    await pages[index].getByRole('button', { name: '加入房间' }).click()
    await expect(pages[index].getByText(roomCode!)).toBeVisible()
    await pages[index].getByRole('button', { name: '准备' }).click()
  }
  await pages[0].getByRole('button', { name: '开始游戏' }).click()
  await expect(pages[0].getByRole('heading', { name: '择将入局' })).toBeVisible()
  for (const context of contexts) await context.close()
})

test('eight-seat invite retains a guest seat after refresh', async ({ browser }) => {
  const hostContext = await browser.newContext()
  const guestContext = await browser.newContext()
  const host = await hostContext.newPage()
  const guest = await guestContext.newPage()
  try {
    await host.goto('/')
    await host.getByLabel('玩家昵称').fill('房主')
    await host.getByLabel('对局模式').selectOption('military-eight')
    await expect(host.getByLabel('对局模式')).toHaveValue('military-eight')
    await host.getByRole('button', { name: '创建多人房间' }).click()
    const roomCode = (await host.locator('.room-code-box strong').textContent())?.trim()
    expect(roomCode).toMatch(/^[A-Z0-9]{6}$/)
    await expect(host.locator('.lobby-seat')).toHaveCount(8)
    await guest.goto('/room/' + roomCode)
    await guest.getByLabel('玩家昵称').fill('来宾')
    await guest.getByRole('button', { name: '加入房间' }).click()
    await guest.getByRole('button', { name: '准备' }).click()
    await expect(host.locator('.lobby-seat').filter({ hasText: '来宾' })).toContainText('已准备')
    await guest.reload()
    await expect(guest.locator('.lobby-seat')).toHaveCount(8)
    await expect(guest.locator('.lobby-seat').filter({ hasText: '来宾' })).toContainText('已准备')
    await host.getByRole('button', { name: '开始游戏' }).click()
    await expect(host.getByRole('heading', { name: '择将入局' })).toBeVisible()
    await expect(guest.getByRole('heading', { name: '择将入局' })).toBeVisible()
  } finally {
    await hostContext.close()
    await guestContext.close()
  }
})

test('military five starts with two humans and three AI seats', async ({ browser }) => {
  const hostContext = await browser.newContext()
  const guestContext = await browser.newContext()
  try {
    const host = await hostContext.newPage()
    const guest = await guestContext.newPage()
    await host.goto('/')
    await host.getByLabel('玩家昵称').fill('房主')
    await host.getByLabel('对局模式').selectOption('military-five')
    await host.getByRole('button', { name: '创建多人房间' }).click()
    await expect(host.getByLabel('房间模式')).toHaveValue('military-five')
    await expect(host.locator('.lobby-seat')).toHaveCount(5)
    const roomCode = (await host.locator('.room-code-box strong').textContent())?.trim()
    expect(roomCode).toMatch(/^[A-Z0-9]{6}$/)
    await guest.goto('/room/' + roomCode)
    await guest.getByLabel('玩家昵称').fill('来宾')
    await guest.getByRole('button', { name: '加入房间' }).click()
    await expect(host.locator('.lobby-seat.human')).toHaveCount(2)
    await guest.getByRole('button', { name: '准备' }).click()
    await host.getByRole('button', { name: '开始游戏' }).click()
    await expect(host.getByRole('heading', { name: '择将入局' })).toBeVisible()
    await host.locator('.general-card').first().click()
    await host.getByRole('button', { name: '确认武将' }).click()
    await guest.locator('.general-card').first().click()
    await guest.getByRole('button', { name: '确认武将' }).click()
    await expect(host.locator('.game-page')).toBeVisible()
    await expect(guest.locator('.game-page')).toBeVisible()
    await expect(host.locator('.player-panel')).toHaveCount(5)
    await expect(guest.locator('.player-panel')).toHaveCount(5)
  } finally {
    await hostContext.close()
    await guestContext.close()
  }
})

test('military five starts with one human and four AI seats', async ({ browser }) => {
  const context = await browser.newContext()
  try {
    const host = await context.newPage()
    await host.goto('/')
    await host.getByLabel('玩家昵称').fill('单人房主')
    await host.getByLabel('对局模式').selectOption('military-five')
    await host.getByRole('button', { name: '创建多人房间' }).click()
    await expect(host.locator('.lobby-seat')).toHaveCount(5)
    await expect(host.locator('.lobby-seat.human')).toHaveCount(1)
    await host.getByRole('button', { name: '开始游戏' }).click()
    await expect(host.getByRole('heading', { name: '择将入局' })).toBeVisible()
    await host.locator('.general-card').first().click()
    await host.getByRole('button', { name: '确认武将' }).click()
    await expect(host.locator('.game-page')).toBeVisible()
    await expect(host.locator('.player-panel')).toHaveCount(5)
  } finally {
    await context.close()
  }
})

test('lobby mode switch preserves joined humans and changes seat count', async ({ browser }) => {
  const hostContext = await browser.newContext()
  const guestContext = await browser.newContext()
  try {
    const host = await hostContext.newPage()
    const guest = await guestContext.newPage()
    await host.goto('/')
    await host.getByLabel('玩家昵称').fill('房主')
    await host.getByRole('button', { name: '创建多人房间' }).click()
    const roomCode = (await host.locator('.room-code-box strong').textContent())?.trim()
    await guest.goto('/room/' + roomCode)
    await guest.getByLabel('玩家昵称').fill('来宾')
    await guest.getByRole('button', { name: '加入房间' }).click()
    await expect(host.locator('.lobby-seat')).toHaveCount(5)
    await host.getByLabel('房间模式').selectOption('military-eight')
    await expect(host.locator('.lobby-seat')).toHaveCount(8)
    await expect(guest.locator('.lobby-seat')).toHaveCount(8)
    await expect(host.locator('.lobby-seat.human')).toHaveCount(2)
    await host.getByLabel('房间模式').selectOption('military-five')
    await expect(host.locator('.lobby-seat')).toHaveCount(5)
    await expect(host.locator('.lobby-seat.human')).toHaveCount(2)
    await expect(guest.locator('.lobby-seat').filter({ hasText: '来宾' })).toHaveCount(1)
  } finally {
    await hostContext.close()
    await guestContext.close()
  }
})

test('military eight enters an eight-seat game and survives guest refresh', async ({ browser }) => {
  const hostContext = await browser.newContext()
  const guestContext = await browser.newContext()
  try {
    const host = await hostContext.newPage()
    const guest = await guestContext.newPage()
    await host.goto('/')
    await host.getByLabel('玩家昵称').fill('房主')
    await host.getByLabel('对局模式').selectOption('military-eight')
    await host.getByRole('button', { name: '创建多人房间' }).click()
    const roomCode = (await host.locator('.room-code-box strong').textContent())?.trim()
    await guest.goto('/room/' + roomCode)
    await guest.getByLabel('玩家昵称').fill('来宾')
    await guest.getByRole('button', { name: '加入房间' }).click()
    await guest.getByRole('button', { name: '准备' }).click()
    await host.getByRole('button', { name: '开始游戏' }).click()
    await host.locator('.general-card').first().click()
    await host.getByRole('button', { name: '确认武将' }).click()
    await guest.locator('.general-card').first().click()
    await guest.getByRole('button', { name: '确认武将' }).click()
    await expect(host.locator('.game-page')).toBeVisible()
    await expect(guest.locator('.game-page')).toBeVisible()
    await expect(host.locator('.player-panel')).toHaveCount(8)
    await expect(guest.locator('.player-panel')).toHaveCount(8)
    await guest.reload()
    await expect(guest.locator('.game-page')).toBeVisible()
    await expect(guest.locator('.player-self')).toContainText('你 · 来宾')
    await expect(guest.locator('.player-panel')).toHaveCount(8)
  } finally {
    await hostContext.close()
    await guestContext.close()
  }
})

test('full eight-human room lets a refreshed browser reclaim its seat', async ({ browser }) => {
  test.setTimeout(120000)
  const contexts = await Promise.all(Array.from({ length: 8 }, () => browser.newContext()))
  try {
    const pages = await Promise.all(contexts.map((context) => context.newPage()))
    await pages[0].goto('/')
    await pages[0].getByLabel('玩家昵称').fill('玩家1')
    await pages[0].getByLabel('对局模式').selectOption('military-eight')
    await pages[0].getByRole('button', { name: '创建多人房间' }).click()
    const roomCode = (await pages[0].locator('.room-code-box strong').textContent())?.trim()
    expect(roomCode).toMatch(/^[A-Z0-9]{6}$/)
    for (let index = 1; index < pages.length; index += 1) {
      await pages[index].goto('/room/' + roomCode)
      await pages[index].getByLabel('玩家昵称').fill('玩家' + (index + 1))
      await pages[index].getByRole('button', { name: '加入房间' }).click()
      await pages[index].getByRole('button', { name: '准备' }).click()
    }
    await expect(pages[0].locator('.lobby-seat.human')).toHaveCount(8)
    await pages[0].getByRole('button', { name: '开始游戏' }).click()
    for (const page of pages) {
      await expect(page.getByRole('heading', { name: '择将入局' })).toBeVisible()
      await page.locator('.general-card').first().click()
      await page.getByRole('button', { name: '确认武将' }).click()
    }
    await expect(pages[7].locator('.game-page')).toBeVisible()
    await expect(pages[7].locator('.player-panel')).toHaveCount(8)
    await pages[7].reload()
    await expect(pages[7].locator('.game-page')).toBeVisible()
    await expect(pages[7].locator('.player-self')).toContainText('你 · 玩家8')
    await expect(pages[7].locator('.player-panel')).toHaveCount(8)
    await expect(pages[0].locator('.player-panel')).toHaveCount(8)
  } finally {
    for (const context of contexts) await context.close()
  }
})
