import {test,expect} from '@playwright/test'
async function start(page:any,request:any,caseName:string){
  const res=await request.post('http://127.0.0.1:8007/audit/fixture/'+caseName);expect(res.ok()).toBe(true)
  const record=await res.json()
  await page.addInitScript((record:any)=>{localStorage.setItem('sanguosha.web.session.v1',JSON.stringify(record));localStorage.setItem('sanguosha.web.speed','normal')},record)
  await page.goto('/')
  await page.getByRole('button',{name:'继续对局',exact:true}).click()
  await expect(page.locator('.game-page')).toBeVisible()
}
test('A AI Cao Cao Slash -> human Liu Bei Dodge, persistent turn and semantic responder',async({page,request})=>{
  await page.setViewportSize({width:1440,height:1000});await start(page,request,'A')
  await expect(page.locator('[data-player-id="p2"] .turn-badge')).toContainText('出牌')
  await expect(page.locator('.event-stage')).toHaveAttribute('data-stage','target',{timeout:20000})
  await page.screenshot({path:'../docs/t18a7/A-trajectory.png'})
  await expect(page.locator('[data-player-id="p1"] .responder-state')).toContainText('响应【杀】',{timeout:20000})
  await expect(page.locator('[data-player-id="p1"] .responder-state')).toContainText('请出【闪】')
  await expect(page.locator('.base-card img')).toHaveAttribute('alt','杀')
  expect((await page.locator('.base-card').boundingBox())!.width).toBeGreaterThanOrEqual(220)
  await page.screenshot({path:'../docs/t18a7/A-slash-response.png'})
  await page.locator('.hand').getByRole('button',{name:/^闪 /}).first().click();await page.getByRole('button',{name:'确定',exact:true}).click()
  await expect(page.locator('.response-card img')).toHaveAttribute('alt','闪')
  await page.screenshot({path:'../docs/t18a7/A-dodge.png'})
  await expect(page.locator('[data-player-id="p1"].responding')).toHaveCount(0)
})
test('B human Slash -> AI seat thinking then visible Dodge',async({page,request})=>{
  await page.setViewportSize({width:1440,height:1000});await start(page,request,'B')
  await page.locator('.hand').getByRole('button',{name:/^杀 /}).click();await page.locator('[data-player-id="p2"].selectable').click()
  const begun=Date.now();await page.getByRole('button',{name:'确定',exact:true}).click()
  await expect(page.locator('[data-player-id="p2"]')).toHaveClass(/responding.*thinking/)
  await expect(page.locator('[data-player-id="p2"] .responder-state')).toContainText('请出【闪】')
  await expect(page.locator('.event-stage')).not.toContainText('思考')
  await expect(page.locator('.response-card img')).toHaveAttribute('alt','闪',{timeout:15000})
  expect(Date.now()-begun).toBeGreaterThanOrEqual(3500)
  await page.screenshot({path:'../docs/t18a7/B-ai-dodge.png'})
})
for(const [caseName,card,response] of [['C','南蛮入侵','杀'],['D','万箭齐发','闪']])test(caseName+' authoritative AOE fanout and ordered response',async({page,request})=>{
  await start(page,request,caseName)
  await expect(page.locator('.base-card img')).toHaveAttribute('alt',card,{timeout:25000})
  await expect(page.locator('.aoe-badge')).toHaveCount(4)
  await expect(page.locator('.event-stage')).toHaveAttribute('data-stage','target')
  await page.screenshot({path:'../docs/t18a7/'+caseName+'-trajectories.png'})
  await expect(page.locator('[data-player-id="p1"] .responder-state')).toContainText('请出【'+response+'】')
  await page.screenshot({path:'../docs/t18a7/'+caseName+'-fanout.png'})
  await page.locator('.hand').getByRole('button',{name:new RegExp('^'+response+' ')}).first().click();await page.getByRole('button',{name:'确定',exact:true}).click()
  await expect(page.locator('[data-player-id="p2"].responding')).toBeVisible({timeout:15000})
  await expect(page.locator('[data-player-id="p1"] .aoe-badge')).toHaveText('已结算')
})
test('E both counter commands and root card stay visible',async({page,request})=>{
  await start(page,request,'E')
  await expect(page.getByRole('button',{name:'使用无懈',exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'不响应',exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'本次不无懈',exact:true})).toBeVisible()
  await expect(page.locator('.base-card img')).toHaveAttribute('alt','南蛮入侵')
  await page.screenshot({path:'../docs/t18a7/E-controls.png'})
  await page.getByRole('button',{name:'本次不无懈',exact:true}).click()
  await expect(page.getByRole('button',{name:'本次不无懈',exact:true})).toHaveCount(0)
})
test('F counter and counter-counter retain original trick and final parity',async({page,request})=>{
  await start(page,request,'F')
  await page.locator('.hand').getByRole('button',{name:/^无懈可击 /}).click();await page.getByRole('button',{name:'使用无懈',exact:true}).click()
  await expect(page.locator('.base-card img')).toHaveAttribute('alt','南蛮入侵')
  await expect(page.locator('.response-card img')).toHaveAttribute('alt','无懈可击')
  await expect(page.locator('.nullification-status')).toContainText('无懈×1')
  await expect(page.locator('.nullification-status')).toContainText('无懈×2',{timeout:20000})
  await expect(page.locator('.nullification-status')).toContainText('锦囊有效')
  await page.screenshot({path:'../docs/t18a7/F-counter-chain.png'})
})
for(const size of [{width:390,height:844},{width:430,height:932}])test('mobile '+size.width+' semantic response and controls visible',async({page,request})=>{
  await page.setViewportSize(size);await start(page,request,'A')
  await expect(page.locator('[data-player-id="p1"] .responder-state')).toContainText('请出【闪】',{timeout:20000})
  await expect(page.getByRole('button',{name:'确定',exact:true})).toBeInViewport()
  await expect(page.locator('.base-card')).toBeInViewport()
  await page.screenshot({path:'../docs/t18a7/mobile-'+size.width+'.png',fullPage:true})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})

for(const size of [{width:390,height:844},{width:430,height:932}])test('eight-player mobile '+size.width+' keeps response and controls readable',async({page,request})=>{
  await page.setViewportSize(size);await start(page,request,'A8')
  await expect(page.locator('.player-panel')).toHaveCount(8)
  await expect(page.locator('[data-player-id="p1"] .responder-state')).toContainText('请出【闪】',{timeout:20000})
  await expect(page.getByRole('button',{name:'确定',exact:true})).toBeInViewport()
  await expect(page.locator('.base-card')).toBeInViewport()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'../docs/t18a7/mobile-eight-'+size.width+'.png',fullPage:true})
})
