import { test, expect } from '@playwright/test'
async function fixture(page: any, eight = false) {
  await page.route('**/src/state/GameContext.tsx*', (r: any) => r.fulfill({contentType:'application/javascript',body:`export function useGame(){return {state:window.__t15State,actions:{returnHome(){},clearError(){},submitDecision(){}}}}`}))
  await page.goto('/e2e/fixtures/t15.html?real&only-lvbu')
  await page.evaluate((eight: boolean) => {const w=window as any,s=w.__t15State;s.pendingRequest=null;s.publicEvents=[];if(eight)for(let i=6;i<=8;i++)s.projection.players.push({...s.projection.players[2],player_id:'p'+i,name:'玩家'+i});w.__t15Render()},eight)
  await expect(page.locator('.player-panel')).toHaveCount(eight?8:5)
}
test('AI action reveal then target; dedicated human response ring and seat deadline',async({page})=>{
  await fixture(page)
  await page.evaluate(()=>{const w=window as any,s=w.__t15State;s.publicEvents=[{event_id:'slash',kind:'CardUsedEvent',source_id:'p2',target_ids:['p1'],definition_id:'basic.slash',card_name:'杀'}];w.__t15Render()})
  await expect(page.locator('.event-stage')).toHaveAttribute('data-stage','reveal')
  await expect(page.locator('.center-action-card img')).toHaveAttribute('alt','杀')
  expect((await page.locator('.center-action-card').boundingBox())!.width).toBeGreaterThan(120)
  await expect(page.locator('.event-stage')).toHaveAttribute('data-stage','target')
  await expect(page.locator('[data-player-id="p1"]')).toHaveClass(/event-target/)
  await page.evaluate(()=>{const w=window as any,s=w.__t15State;s.pendingRequest={request_id:'human',player_id:'p1',request_type:'respond_with_card',prompt:'请打出闪',choices:[],eligible_card_ids:[],allowed_player_ids:[],min_count:0,max_count:1,allow_pass:true,remaining_ms:12400};w.__t15Render()})
  await expect(page.locator('[data-player-id="p1"]')).toHaveClass(/active.*responding/)
  await expect(page.locator('[data-player-id="p1"] .seat-timer')).toContainText('12.')
  const timerBox = (await page.locator('[data-player-id="p1"] .seat-timer').boundingBox())!
  expect(timerBox.y + timerBox.height).toBeLessThanOrEqual(page.viewportSize()!.height)
  await expect(page.locator('.decision-prompt .timer')).toHaveCount(0)
  await page.screenshot({path:'../docs/t18a6/human-response.png'})
  await page.evaluate(()=>{const w=window as any;w.__t15State.pendingRequest=null;w.__t15Render()})
  await expect(page.locator('.seat-timer')).toHaveCount(0)
})
test('eight seats continuous responses show Dodge Peach skill and one public waiting seat',async({page})=>{
  await fixture(page,true)
  for(const [index,definition,label] of [[2,'basic.dodge','闪'],[3,'basic.peach','桃']] as const){
    await page.evaluate(({index,definition})=>{const w=window as any,s=w.__t15State;s.projection.waiting={key:'r'+index,player_id:'p'+index,responding:true,thinking:true,remaining_ms:2400};s.publicEvents=[];w.__t15Render()},{index,definition})
    await expect(page.locator('.responding')).toHaveCount(1)
    await expect(page.locator('.thinking')).toHaveCount(1)
    await expect(page.locator('[data-player-id="p'+index+'"] .seat-timer')).toBeVisible()
    await expect(page.locator('.event-stage')).not.toContainText('思考')
    await page.evaluate(({index,definition})=>{const w=window as any,s=w.__t15State;s.projection.waiting=null;s.publicEvents=[...s.publicEvents,{event_id:'response'+index,kind:'CardRespondedEvent',source_id:'p'+index,definition_id:definition}];w.__t15Render()},{index,definition})
    await expect(page.locator('.center-action-card img')).toHaveAttribute('alt',label)
    await expect(page.locator('.seat-timer')).toHaveCount(0)
    await page.screenshot({path:'../docs/t18a6/eight-'+label+'.png'})
    await expect(page.locator('.center-action-card')).toHaveCount(0)
  }
  await page.evaluate(()=>{const w=window as any;w.__t15State.publicEvents=[{event_id:'skill',kind:'SkillEvent',source_id:'p3',skill_name:'明策',target_ids:['p4']}];w.__t15Render()})
  await expect(page.locator('.event-stage')).toContainText('明策')
  await expect(page.locator('[data-player-id="p3"]')).toHaveClass(/presenting-action/)
  await page.screenshot({path:'../docs/t18a6/eight-skill.png'})
})

test('real human Slash opens an AI response seat then displays Dodge', async ({page}) => {
  test.setTimeout(90000)
  await page.goto('/?seed=16')
  await page.getByLabel('玩家昵称').fill('真人杀AI响应验收')
  await page.getByRole('button',{name:'单人游戏',exact:true}).click()
  await page.locator('.general-card').first().click()
  await page.getByRole('button',{name:'确认武将',exact:true}).click()
  await expect(page.locator('.game-page')).toBeVisible()
  await page.getByRole('button',{name:/^杀 /}).first().click()
  await page.locator('[data-player-id="p2"].selectable').click()
  const started=Date.now()
  await page.getByRole('button',{name:'确定',exact:true}).click()
  await expect(page.locator('[data-player-id="p2"]')).toHaveClass(/responding/)
  await expect(page.locator('[data-player-id="p2"]')).toHaveClass(/thinking/)
  await expect(page.locator('[data-player-id="p2"] .seat-timer')).toBeVisible()
  await expect(page.locator('.center-action-card img')).toHaveAttribute('alt','杀')
  await page.screenshot({path:'../docs/t18a6/real-human-slash-ai-wait.png'})
  await expect(page.locator('.center-action-card img')).toHaveAttribute('alt','闪',{timeout:15000})
  expect(Date.now()-started).toBeGreaterThanOrEqual(2000)
  await page.screenshot({path:'../docs/t18a6/real-ai-dodge.png'})
})
