import { test, expect } from '@playwright/test'

for (const [mode, seats] of [['duel-1v1', 2], ['team-2v2', 4]] as const) {
  test('T20 real single player draft and AI autofill ' + mode, async ({ page }) => {
    await page.goto('/?seed=20')
    await page.getByLabel('对局模式').selectOption(mode)
    await page.getByRole('button', { name: '单人游戏', exact: true }).click()
    await expect(page.locator('.general-card')).toHaveCount(10)
    await expect(page.locator('.identity-reveal')).toContainText(mode === 'duel-1v1' ? '玩家A' : 'A队')
    await page.locator('.general-card').first().click()
    await page.getByRole('button', { name: '确认武将' }).click()
    await expect(page.locator('.game-page')).toBeVisible()
    await expect(page.locator('.player-panel')).toHaveCount(seats)
    await page.screenshot({ path: '../docs/t20/' + mode + '-desktop.png' })
    await page.setViewportSize({ width: 390, height: 844 })
    await page.screenshot({ path: '../docs/t20/' + mode + '-mobile.png' })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  })

  test('T20 protected test mode self selection ' + mode, async ({ page }) => {
    await page.goto('/?seed=20')
    await page.getByLabel('对局模式').selectOption(mode)
    await page.getByRole('button', { name: '测试模式', exact: true }).click()
    await page.getByLabel('测试权限码').fill('fixture-only-code')
    await page.getByRole('button', { name: '验证', exact: true }).click()
    await page.getByRole('button', { name: '创建测试房', exact: true }).click()
    await expect(page.locator('.general-card')).toHaveCount(108)
    await page.getByLabel('搜索武将或技能').fill('曹操')
    await page.locator('.general-card').first().click()
    await page.getByRole('button', { name: '确认武将' }).click()
    await expect(page.locator('.game-page')).toBeVisible()
    await expect(page.locator('.player-panel')).toHaveCount(seats)
    await expect(page.locator('.player-self')).toHaveAttribute('data-character-id', 'caocao')
  })
}

test('T20 two humans are enemies, autofill and refresh preserve team', async ({ browser }) => {
  const a = await browser.newContext(), b = await browser.newContext()
  try {
    const host = await a.newPage(), guest = await b.newPage()
    await host.goto('/?seed=20')
    await host.getByLabel('玩家昵称').fill('A真人')
    await host.getByLabel('对局模式').selectOption('team-2v2')
    await host.getByRole('button', { name: '创建多人房间', exact: true }).click()
    const code = await host.locator('.room-code-box strong').textContent()
    await guest.goto('/room/' + code)
    await guest.getByLabel('玩家昵称').fill('B真人')
    await guest.getByRole('button', { name: '加入房间', exact: true }).click()
    await expect(host.locator('.lobby-seat').nth(0)).toContainText('A队')
    await expect(host.locator('.lobby-seat').nth(1)).toContainText('B队')
    await guest.getByRole('button', { name: '准备', exact: true }).click()
    await host.getByRole('button', { name: '开始游戏', exact: true }).click()
    await expect(guest.locator('.general-card')).toHaveCount(10)
    const chosen = await host.locator('.general-card strong').first().textContent()
    await host.locator('.general-card').first().click()
    await host.getByRole('button', { name: '确认武将' }).click()
    await guest.locator('.general-card').filter({ hasNotText: chosen ?? '' }).first().click()
    await guest.getByRole('button', { name: '确认武将' }).click()
    await expect(host.locator('.player-panel')).toHaveCount(4)
    await expect(guest.locator('.player-self')).toHaveAttribute('data-team-id', 'B')
    const character = await guest.locator('.player-self').getAttribute('data-character-id')
    await guest.reload()
    await guest.getByRole('button', { name: '继续对局', exact: true }).click()
    await expect(guest.locator('.player-self')).toHaveAttribute('data-team-id', 'B')
    await expect(guest.locator('.player-self')).toHaveAttribute('data-character-id', character!)
    await expect(guest.locator('.player-panel')).toHaveCount(4)
    await expect(host.locator('.player-self')).toHaveAttribute('data-team-id', 'A')
  } finally {
    await Promise.allSettled([...a.pages(), ...b.pages()].map(p => p.goto('about:blank')))
    await a.close(); await b.close()
  }
})
